# Generated by Django 6.0.3 on 2026-05-08 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_remove_order_paid_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paymongo_source_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='checkout_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='order',
            name='paymongo_link_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
