# Generated by Django 6.0.3 on 2026-04-28 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_laundryshop_order_notification_shopaddon_shopreview_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('new_order', 'New Order'), ('status_update', 'Status Update'), ('rider_assigned', 'Rider Assigned'), ('order_delivered', 'Order Delivered'), ('order_rejected', 'Order Rejected'), ('shop_update', 'Shop Update'), ('order_accepted', 'Order Accepted'), ('ready_for_delivery', 'Ready for Delivery')], max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rider_accepted', 'Rider Accepted'), ('picked_up', 'Picked Up'), ('washing', 'Washing'), ('drying', 'Drying'), ('ready', 'Ready for Delivery'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
