# Generated by Django 6.0.3 on 2026-05-03 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_order_out_for_delivery_at_order_picked_up_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='has_review',
            field=models.BooleanField(default=False),
        ),
    ]
