# Generated by Django 6.0.3 on 2026-05-19 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_order_has_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivered_to_shop_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='picked_up_from_shop_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rider_accepted', 'Rider Accepted'), ('picked_up', 'Picked Up'), ('delivered_to_shop', 'Delivered to Shop'), ('washing', 'Washing'), ('drying', 'Drying'), ('ready', 'Ready for Delivery'), ('picked_up_from_shop', 'Picked Up from Shop'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='pending', max_length=25),
        ),
    ]
